Hello world 

this is vim and it is awesom

press i to get into insert mode

press esc to get out of insert mode

i wrote something but did not want to save it,press esc q! so as not to save the file contents

navigation using vim use the hjkl keys

h goes left

j goes down

k goes up

l goes right

some other methods to enter insert mode
vim is awesome

appending before letter i because i pressed i i insert

a append after the letter i selected because i pressed letter a  letter selected

CAPITAL I TO GO TO THE BEGINING OF THE LINE

CAPITAL A TO NAVIGATE TO THE END OF THE LINE

o means open a new line below the line I am curently on

CAPITAL O MEANS OPEN A NEW LINE ABOVE THE LINE I AM CURRENTLY ON

w jump to next word when in normal mode

b jump previous word some_block_of_code_here is awesome using vim Copying is called yanking in vim 

r is for replacing a letter 

R capital is for replacing shole word 

replace this here word words aresome AWESOME again

cw in order to replace the whole word

This is vim hello it is practicaltest test and it works nice

i can also start from center of the word

center of the ward

Ri wonna see this text getting overwritten because i was using capital R mode
jump 3 words using vim i use 3w
there are some words to jump here so i wonna jump
change 7 words using c7w
i change 3words and i want to change about 7 words am i am testing it btw
4j move four lines down

some lines here

some other lines here





here here 



here
also
here


here 
too




awe
werqw

UPPER CASE C REPLACES EVERYTHING THAT COMES AFTER IT
testing for uppercase C behaviour I REPLACED HERE WITH UPPERCASE C that also enters insert mode
UPPERCASE D DELETED REST OF THE LINE WITHOUT ENTERING INSERT MODE
I deleted what was here next 
dw deletes the word without entering the insert mode 
d4w deletes four words and does not enter insert mode
cc to replace the whole line
dd to delete the whole line
some words were here but


4dd to deete 4 lines
8cc to change 8 lines just magic of vim

for (int i = 0; i < 100; i++){
}

undoing stuff in vim using the u key
CTRL + R - Redo
5U UNDO LAST 5 CHANGES
7 CTRL + R Redo seven last things
alternative of cw when at the center of the line
ciw change inner word
diw delete inner word

NeuralNine video Editing Tutorials
Neuralnine video editing tutoriasl_changed
Neuralnine video editing deleted







for (jsdsadjasdfjasasjhfgasufgasufasf){
all nonsense changed here
}
ci)
ci(
ci[
ci]
ci{
ci}
% to jump to bracket
c% change untill bracket
for 
yes nonsense changed

press gg to go to the begining of the file
press G to go to end of the file

press 7 and G to move to line 7 or :26
$ navigate to end of line
0 navigate to the begining of line without entering insert mode



pasting and copying stuff
enter visual mode using v key d for deleting c to change y to yank
yy yank whole line
5yy yank next 5 lines
5yy yank next 5 lines
5yy yank next 5 lines
5yy yank next 5 lines
5yy yank next 5 lines
9p paste nine times
y2w for yank 2 words


i have some 
stuff to
select over here 
so that 
i can paste it
down someehere
nice 
okay


pasting and copying stuff
enter visual mode using v key

i have some 
stuff to
select over here 
so that 
i can paste it
down someehere
nice 
okay

changed here with visual mode

pasted
pasted
test to paste above test to paste above
and 
paste beforeYANK SOME NONSENSE HERE
YANK SOME NONSENSE HEREYANK SOME NONSENSE HERE
YANK SOME NONSENSE HEREYANK SOME NONSENSE HERE
YANK SOME NONSENSE HERE
YANK SOME NONSENSE HEREYANK SOME N

ONSENSE HEREYANK SOME NONSENSE HERE
vkshdshakdiguwq

vkshdshakdiguwq

vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq

vkshdshakdiguwq



vkshdshakdiguwq

vkshdshakdiguwq

vkshdshakdiguwq

vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwqdd
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq
vkshdshakdiguwq




jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
jhdsd
jhdsd
jhdsd
jhdsd
fjqwojr
qwrhqwkh
fjqwojr
qwrhqwkh
fjqwojr
qwrhqwkh
fjqwojr
qwrhqwkh

jhdsd
jhdsd
fjqwojr
qwrhqwkh
fjqwojr
qwrhqwkh



jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh


jhdsd
fjqwojr
qwrhqwkh
jhdsd
fjqwojr
qwrhqwkh
<<<
I have some words here
<ave some have some have some have some have some have some have some 
(hdehwdhwe copy inside contents){
<Down>
sahdaskhdas

sdljqwojd
qwljedqw
qwhejioqwhe
qwheiqwoejh
qwjeigqwe
qwheiq  
qwhei   h

}
hdehwdhwe copy inside contents
sdsa



UPPERCASE Y IS YANKING THE WHOLE LINE
UPPERCASE Y IS YANKING THE WHOLE LINEUPPERCASE Y IS YANKING THE WHOLE LINE
UPPERCASE Y IS YANKING THE WHOLE LINE
SHIFT + v visula line
ctrl + v visual block
zz to have your seletion at the center of the screen

n visual mode you can now use 50 j then d to delete those lines to go down and delete those lines
 word
d word
 word
 word
 word


  qwetrqwe
  t
  weq

  rqw
  et
  qwt
  wer
  y
  eru
  yer
change last operation by pressing .
> - shift right
< - shift left
=- Indent
>> & << Shift Line
= - Indent line
To indent a whole file gg = G 
gg d G delete the whole file

/word search for word
n -Next occurence
N previous occurence
# previous token occurence
+ - next token occurence
:s/old/new/g -Replace
:%s/old/new/g -Replace everything
set number
set relativenumber
colorscheme scheme
et tabstop = 4
set autoindent
set mouse = a
set mouse =""

kchange change change jashdfas askhdfiquwh qwuihrqw
hkchange wdiqwhd qwdhqwihew wqehiqwhe wqehiqwh hwdiqwhd qwdhqwihew wqehiqwhe wqehiqwh 
fr (int i = 0;i < 100; i++){
  dhwqhdqwdqw
    qwdqwehoqwje
    qwehiqwheqw
    iqwyeiyqw
    qwehiqwuey
    oiueqwoue
    qweguqwe
    qiugeiqe
    qigweuqwge
    qgweuqwg




}
